name: Siege_ChatSystem
main: me.x3DGosling.Siege_ChatSystem.Main
version: 1.0
permission-message: You don't have permission to use this.
commands:
#============
  me:
  f:
  a:
  h:
  pm:
  tell:
  msg:
#============